### PR TITLE
Avatar-Badge Comp

### PR DESCRIPTION
**Pull request by Husain01**

### CODE REVIEW

**Comment by Kevin-Solomon** [comment]
Looks good husain!
Nice usage of variables and calc function.

**Review by Kevin-Solomon — APPROVED** [review]
Looks good husain!
Nice usage of variables and calc function.

**Comment by Husain01** [comment]
> Looks good husain! Nice usage of variables and calc function.

Thank you. Could you also approve it.

**Comment by Kevin-Solomon** [comment]
> > Looks good husain! Nice usage of variables and calc function.
> 
> Thank you. Could you also approve it.

I have approved the changes husain.

**Review by kart-c — APPROVED** [review]
Great work Husain. Really like your UI

**Review by mohammed-sas — APPROVED** [review]
everything is fine

**Review by RakshaPawar108 — COMMENTED** [review]
Great work on the UI Husain! Loved the design and the code is also super clean.  Just a suggestion, give a small margin on the right side of the content on smaller screens as the content is responsive but sticking to the right side of the screen. Amazing work otherwise!!

**Review by RakshaPawar108 — APPROVED** [review]

**Pull request merged**
